import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { FlipWords } from "@/components/ui/flip-words";
import { NavbarDemo } from "./ui/nav";
import { Hero } from "./ui/hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const words = ["better", "cute", "beautiful", "modern"];

  return (
    <html lang="en" className="dark dark:bg-black">
      <body className={inter.className + " w-screen"}>
        <div className=" w-full "> <NavbarDemo/> </div>
        <Hero/>
        <div>{children}</div></body>
    </html>
  );
}
