import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { FlipWords } from "@/components/ui/flip-words";
import { NavbarDemo } from "./ui/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const words = ["better", "cute", "beautiful", "modern"];

  return (
    <html lang="en" className="dark dark:bg-black">
      <body className={inter.className + " w-screen"}>
        <div className=" w-full dark:bg-black"><NavbarDemo/></div>
        <div className="h-[40rem] flex w-full dark:bg-black justify-center items-center px-4">
          <div className="text-4xl mx-auto font-normal text-neutral-600 dark:text-neutral-400">
            Build
            <FlipWords words={words} /> <br />
            websites with Aceternity UI
          </div>
        </div>
        <div>{children}</div></body>
    </html>
  );
}
